events {
    worker_connections 1024;
}

http {
    mime_types {
        text/html html htm;
        text/plain txt;
        application/json json;
    }

    server {
        listen 80;
        server_name _;

        root /usr/share/nginx/html;
        index about.html;

        location / {
            try_files $uri $uri/ =404;
        }

        error_page 404 /404.html;
    }
}
